# Generated by Django 5.2 on 2026-05-19 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
                ("nationalite", models.CharField(blank=True, max_length=100)),
                ("adresse", models.TextField()),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("instagram", models.CharField(blank=True, max_length=100)),
                ("nom_responsable", models.CharField(blank=True, max_length=200)),
                ("tel_responsable", models.CharField(blank=True, max_length=20)),
                ("date_inscription", models.DateField(auto_now_add=True)),
                ("archive", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_inscription"],
            },
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "federation",
                    models.CharField(
                        choices=[
                            ("CFJJB", "CFJJB"),
                            ("FFJDA", "FFJDA"),
                            ("FFL", "FFL"),
                        ],
                        max_length=10,
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=50)),
                ("date_expiration", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licences",
                        to="membres.membre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("certif_medical", "Certificat médical"),
                            ("photo_identite", "Photo d'identité"),
                            ("autorisation_parentale", "Autorisation parentale"),
                            ("fiche_inscription", "Fiche d'inscription"),
                            ("reglement", "Règlement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("url_fichier", models.TextField()),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
                ("date_expiration", models.DateField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="membres.membre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ceinture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("blanche", "Blanche"),
                            ("bleue", "Bleue"),
                            ("violette", "Violette"),
                            ("marron", "Marron"),
                            ("noire", "Noire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nom_prof", models.CharField(max_length=150)),
                ("date_obtention", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ceintures",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_obtention"],
            },
        ),
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("mensuel", "Mensuel"), ("annuel", "Annuel")],
                        max_length=10,
                    ),
                ),
                ("date_debut", models.DateField()),
                (
                    "nombre_mois",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnements",
                        to="membres.membre",
                    ),
                ),
            ],
        ),
    ]
