# Generated by Django 5.2 on 2026-05-21 07:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="fichier",
            field=models.FileField(blank=True, upload_to="documents/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="url_fichier",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="UploadToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_tokens",
                        to="membres.membre",
                    ),
                ),
            ],
        ),
    ]
