# Generated by Django 5.2 on 2026-05-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0002_document_fichier_alter_document_url_fichier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membre",
            name="dossier_valide",
            field=models.BooleanField(default=False),
        ),
    ]
