# Generated by Django 5.2 on 2026-05-19 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "moyen",
                    models.CharField(
                        choices=[
                            ("cheque", "Chèque"),
                            ("tpe", "TPE"),
                            ("especes", "Espèces"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_saisis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
