# Generated by Django 5.2 on 2026-05-19 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nom", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[("super_admin", "Super Admin"), ("staff", "Staff")],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "staff",
                "verbose_name_plural": "staff",
            },
        ),
    ]
